### PR TITLE
Changed --config to --profiles

### PR DESCRIPTION
**Pull request by Rishy-09**
changed --config to --profiles only
tested on Windows

### CODE REVIEW

**Comment by MikeBirdTech** [comment]
@Rishy-09! Thank you for doing this!

Looks like I didn't cover everything in the issue, my bad. 

The flag is `--profiles` when opening the directory of profiles.
The flag is `--profile PROFILE` when the user is applying a certain profile.

If you run `interpreter --help` it outputs all the flags. One I would love to see covered is `--reset_profile` because some users will find that very helpful. Would you mind adding it to the PR?

You can read more in the current docs: https://docs.openinterpreter.com/settings/profiles

Let me know if you have any questions. Thanks again for your help and contribution!

**Comment by Rishy-09** [comment]
I would like to work on this issue, even though it is my very first contribution. Could you please provide me with some additional information or tips that I can follow to resolve this issue? Thank you for your guidance!

**Comment by MikeBirdTech** [comment]
Of course! Happy to help with your contributions @Rishy-09 

My biggest tip is to **use OI** in order to write good documentation. 

The main objective of documentation is to teach users how to properly use OI. So by using OI and experiencing what it does, you are learning and are able to teach it to others through the documentation. Take notes as you experiment to help with your understanding. It helps to read the documentation too. Is the current documentation understandable? Can it be more clear? Are there other use-cases that can be included?

Some questions to explore:
When you run `interpreter --profiles` what happens? Does the documentation explain the function correctly? Can it be explained more clearly?

What about `interpreter --profile`? Are there any errors or messages? Do you need to include any arguments? If so, what is the argument? Would a brand new user of OI be able to use this flag after they read the documentation?

Are there any other flags/arguments related to `profiles`? For example, is `--reset_profile` mentioned in the documentation? Users would want to know what this does, so you should experiment with it to see what it does, because it might perform differently if you use it with/without extra arguments.

And finally, don't hesitate to use tools like ChatGPT, or to talk to people in the OI Discord. There are many people who have lots of knowledge about OI who like to share and teach others. The entire community benefits from good documentation, so it is an important part of the project and many of us are happy to help.

Good luck and thank you!

**Comment by MikeBirdTech** [comment]
@Rishy-09 How are you making out with this PR? Do you have any questions?

**Comment by Rishy-09** [comment]
I apologize, but it seems that I'm encountering difficulties with this task. Perhaps it's too early for me to fully grasp it. There are several aspects that I'm having trouble interpreting, and I believe I'll need more time to work through them. It might be best if you could close this request or take any necessary actions. Thank you for your cooperation, and I'm sorry for any delays caused. Despite this, I find this project amazing to work on and play around.

**Comment by MikeBirdTech** [comment]
Thanks for letting us know @Rishy-09 

Hope to see a PR from you in the future. Best of luck!!

**Pull request closed without merging**
