### PR TITLE
open interperter 505

### PR DESCRIPTION
**Pull request by Jaytru505**
### Pre-Submission Checklist (optional but appreciated):

- [x] I have included relevant documentation updates (stored in /docs)
- [x] I have read `docs/CONTRIBUTING.md`
- [x] I have read `docs/ROADMAP.md`

### OS Tests (optional but appreciated):

- [ ] Tested on Windows
- [ ] Tested on MacOS
- [ ] Tested on Linux

### CODE REVIEW

**Comment by Jaytru505** [comment]
update

**Review by Jaytru505 — COMMENTED** [review]
comment

**Comment by Notnaton** [comment]
What is going on here? 😅

**Comment by Jaytru505** [comment]
request pull request

**Review by Jaytru505 — COMMENTED** [review]
reviewed

**Review by Jaytru505 — COMMENTED** [review]
reviewed

**Pull request closed without merging**
