### PR TITLE
Updated fast mode to gpt-4o-mini & Profile version updated

### PR DESCRIPTION
**Pull request by CyanideByte**
### Describe the changes you have made:
- Updated all usages of gpt-3.5-turbo to gpt-4o-mini because its cheaper and more capable
- Updated a few leftover defaults from gpt-4-turbo to gpt-4o
- Added gpt-4o-mini to list of models that ask user for openai key
- Updated version numbers on fast.yaml and vision.yaml profiles

### Reference any relevant issues (e.g. "Fixes #000"):
- Fixed "We have updated our profile file format. Would you like to migrate your profile file to the new format? No data will be lost."

### Pre-Submission Checklist (optional but appreciated):

- [ ] I have included relevant documentation updates (stored in /docs)
- [x] I have read `docs/CONTRIBUTING.md`
- [x] I have read `docs/ROADMAP.md`

### OS Tests (optional but appreciated):

- [x] Tested on Windows
- [ ] Tested on MacOS
- [ ] Tested on Linux

### CODE REVIEW

**Comment by KillianLucas** [comment]
Nice, huge upgrade to all of those profiles. (wondering if it makes sense to default to 4o-mini? it's my default now.)

**Comment by drhouse** [comment]
+1 for 4o-mini being the default, I recommend it in this post #1415

**Comment by CyanideByte** [comment]
I haven't personally tested much of 4o-mini yet. Does it feel strong enough to handle most tasks?

**Comment by drhouse** [comment]
> I haven't personally tested much of 4o-mini yet. Does it feel strong enough to handle most tasks? It being dirt cheap is definitely a plus though.

I honestly don't know what other option there really is, other commercial LLM's are either too expensive for regular use or, in my experience, free local LLM's aren't smart enough yet, the only current realistic balance is 4o-mini... of course I'd always like to hear of a better option

**Pull request merged**
