### PR TITLE
Create manual.yml

### PR DESCRIPTION
**Pull request by Jaytru505**
workflows commit change

### Pre-Submission Checklist (optional but appreciated):

- [ ] I have included relevant documentation updates (stored in /docs)
- [ ] I have read `docs/CONTRIBUTING.md`
- [ ] I have read `docs/ROADMAP.md`

### OS Tests (optional but appreciated):

- [ ] Tested on Windows
- [ ] Tested on MacOS
- [ ] Tested on Linux

### CODE REVIEW

**Comment by Jaytru505** [comment]
pull draft review

**Review by Jaytru505 — COMMENTED** [review]
review

**Comment by MikeBirdTech** [comment]
@Jaytru505 what is the purpose of this?

**Review by Jaytru505 — COMMENTED** [review]
commit

**Comment by Jaytru505** [comment]
create pull request

**Pull request closed without merging**
