### PR TITLE
Create ci.yml

### PR DESCRIPTION
**Pull request by Jaytru505**
### Pre-Submission Checklist (optional but appreciated):

- [x] I have included relevant documentation updates (stored in /docs)
- [x] I have read `docs/CONTRIBUTING.md`
- [x] I have read `docs/ROADMAP.md`

### OS Tests (optional but appreciated):

- [x] Tested on Windows
- [ ] Tested on MacOS
- [ ] Tested on Linux

### CODE REVIEW

**Comment by KillianLucas** [comment]
Hey @Jaytru505! What does Flutter do again?

**Comment by Jaytru505** [comment]
> Hey @Jaytru505! What does Flutter do again?
flutter is a platform called flutterflow it allows developers to innovate there ideas into flutter applications for for a number of cross-platforms making it a popular choice to develop in it's own unique way.

**Comment by Jaytru505** [comment]
lets have at it

**Comment by Jaytru505** [comment]
update pull request

**Review by Jaytru505 — COMMENTED** [review]
update reviewed

**Comment by Jaytru505** [comment]
reopened

**Review by Jaytru505 — COMMENTED** [review]
bypass

**Pull request closed without merging**
