### PR TITLE
Created the snowpark profile for letting open interpreter connect to a user's snowflake account

### PR DESCRIPTION
**Pull request by tx-smitht**
### Describe the changes you have made:
I created a profile to let users work with their Snowflake data using OI

### Pre-Submission Checklist (optional but appreciated):

- [ X] I have included relevant documentation updates (stored in /docs)
- [ X] I have read `docs/CONTRIBUTING.md`
- [ X] I have read `docs/ROADMAP.md`

### OS Tests (optional but appreciated):

- [ ] Tested on Windows
- [X ] Tested on MacOS
- [ ] Tested on Linux

### CODE REVIEW

**Comment by MikeBirdTech** [comment]
Thanks @tx-smitht!

@KillianLucas Any feedback on this new profile?

**Comment by KillianLucas** [comment]
This is awesome @tx-smitht! Basically a Snowflake integration, if you want to add it to docs/integrations. Merging!

P.S. It would be great if you could talk about this on Twitter or somewhere, then we can retweet you— I feel like profiles are a great way to extend OI for specific use cases, would be great to inspire more people to do that.

**Comment by tx-smitht** [comment]
@KillianLucas on it. ill let you know

**Comment by tx-smitht** [comment]
> This is awesome @tx-smitht! Basically a Snowflake integration, if you want to add it to docs/integrations. Merging!
> 
> P.S. It would be great if you could talk about this on Twitter or somewhere, then we can retweet you— I feel like profiles are a great way to extend OI for specific use cases, would be great to inspire more people to do that.

Post with youtube video
https://x.com/tx_smitht/status/1802156524833546553

**Pull request merged**
