### PR TITLE
Create examples directory

### PR DESCRIPTION
**Pull request by MikeBirdTech**
### Describe the changes you have made:
Added a new top level directory for examples

### Reference any relevant issues (e.g. "Fixes #000"):
The community wants examples, so let's give them examples!

### Pre-Submission Checklist (optional but appreciated):

- [x] I have included relevant documentation updates (stored in /docs)
- [x] I have read `docs/CONTRIBUTING.md`
- [x] I have read `docs/ROADMAP.md`

### OS Tests (optional but appreciated):

- [ ] Tested on Windows
- [x] Tested on MacOS
- [ ] Tested on Linux

### CODE REVIEW

**Comment by KillianLucas** [comment]
I love this idea @MikeBirdTech! Could you add to this folder the example google colab notebook, the .ipynb? If there's anything else like that, just simple examples, I think it would be great to have at least 1 in there.

**Comment by LiquidMovz** [comment]
I would love to see any examples of using subscription online model for code steal and Gemini Flash 😀

**Comment by MikeBirdTech** [comment]
> I would love to see any examples of using subscription online model for codestral and Gemini Flash 😀
> 
> I'll contribute if I can figure out how to get it to stop defaulting to OpenAI, I'm 2 16 hour days into it so far...

Do you mean in the command line or as a Python library?

CLI => `interpreter --local`
Python => see the `local3.ipynb` in the PR

**Comment by KillianLucas** [comment]
Nice, thanks for the new examples @MikeBirdTech. Does this work on Google Colab though? I think same as the main example repo, it would be good to also host it on Google Colab and let people test it without installing anything!

**Comment by LiquidMovz** [comment]
> > I would love to see any examples of using subscription online model for codestral and Gemini Flash 😀
> 
> > 
> 
> > I'll contribute if I can figure out how to get it to stop defaulting to OpenAI, I'm 2 16 hour days into it so far...
> 
> 
> 
> @LiquidMovz 
> 
> Do you mean in the command line or as a Python library?
> 
> 
> 
> CLI => `interpreter --local`
> 
> Python => see the `local3.ipynb` in the PR

I meant to be able to access the online subscriptions...I did figure it out with adding profiles, but took a lot of trial and error.

If there were samples, it would make life easier for others.

If you like I could cleanse and upload mine...I have mistral-large and Codestral working...lmk

**Comment by MikeBirdTech** [comment]
@KillianLucas updated the local3 notebook

@LiquidMovz Please feel free to make a PR with your examples. More will definitely help the community!

**Comment by KillianLucas** [comment]
Nice!! Thanks Mike. I have a feeling the Local Colab notebook will be huge— infinite, free, destructible sandbox.

**Pull request merged**
