### PR TITLE
Update lmc-messages.mdx to include audio information 

### PR DESCRIPTION
**Pull request by andrewfr**
adding information for sending LMC audio messages

### Pre-Submission Checklist (optional but appreciated):

- [ ] I have included relevant documentation updates (stored in /docs)
- [x] I have read `docs/CONTRIBUTING.md`
- [x] I have read `docs/ROADMAP.md`

### OS Tests (optional but appreciated):

- [ ] Tested on Windows
- [ ] Tested on MacOS
- [ ] Tested on Linux

### CODE REVIEW

**Comment by andrewfr** [comment]
I had trouble finding information on sending audio from a client to the 01 Light. So I looked the esp32 code and read websocket documentation. I could add sample code

**Comment by MikeBirdTech** [comment]
Thanks @andrewfr!

@KillianLucas I would love to get your thoughts on have `audio` as the type for an LMC

**Comment by andrewfr** [comment]
> Thanks @andrewfr!
> 
> @KillianLucas I would love to get your thoughts on have `audio` as the type for an LMC

Hi @MikeBirdTech @KillianLucas what I would say is confirm that the binary that websocket takes is WAV. I've opened up WAV files and set them straight without stripping the header.

**Comment by KillianLucas** [comment]
This is technically only for the 01, but we will be merging that in soon! Many thanks @andrewfr for adding this.

**Pull request merged**
